name: GeneratedApp
description: A generated Flutter project.

dependencies:
  intl: ^0.15.7
  expressions: ^0.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
  - lib/images/def.png
  - lib/images/menu.png
  - lib/images/wallpaper.png
  - lib/images/google_logo.png
  - lib/images/Gmail-icon.png
  - lib/images/phone.png
  - lib/images/calculator.png
  - lib/images/music.png
  - lib/images/settings.png
  - lib/images/clock.png