on:
  push:
    branches: [ master ]
    paths-ignore: "*.md"
  pull_request:
    branches: [ master ]
name: Deploy to GitHub Pages
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Cache Flutter
      id: flutter-cache-web
      uses: actions/cache@v1.1.2
      with:
        # A directory to store and save the cache
        path: $GITHUB_WORKSPACE/lib/flutter
        # An explicit key for restoring and saving the cache
        key: flutter
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - name: Setup Flutter
      if: "${{steps.flutter-cache.outputs.cache-hit != 'true'}}"
      run: |
        cd $GITHUB_WORKSPACE
        git clone https://github.com/flutter/flutter.git lib/flutter
        cd lib/flutter
        git checkout v1.12.13+hotfix.9 # <--- Flutter version to use
        #./bin/flutter channel master # for web build
        #./bin/flutter upgrade
        ./bin/flutter config --enable-web
        cd $GITHUB_WORKSPACE #be ready for the build job
    - name: Flutter Doctor; set path
      run: |
        export PATH="$PATH:$GITHUB_WORKSPACE/lib/flutter/bin"
        flutter doctor
        echo ::set-env name=PATH::$PATH
    - name: Get dependencies
      run: flutter pub get #TODO: figure out how to cache this
    #- name: Run test
    #  run: flutter test
    # It uses the tests under $GITHUB_WORKSPACE/tests, which don't exist
    - name: Build for web
      run: flutter build web
    - name: Upload release to GitHub Pages
      #if: "${{github.event_name == 'push'}}"
      uses: crazy-max/ghaction-github-pages@v2.0.1
      with:
        build_dir: build/web
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
